language: node_js
node_js:
  - "lts/*"
install:
  - yarn
script:
  - yarn predeploy
  - yarn test
after_success:
  - yarn codacy
deploy:
  - provider: script
    script: "./internals/scripts/deploy.sh"
    skip_cleanup: true
    on:
      branch: master
      tags: true

cache: yarn
