language: node_js
node_js:
  - "lts/*"
install:
  - yarn
before_deploy:
  - yarn predeploy
  - yarn test
  - yarn test:coverage
deploy:
  - provider: script
    script: "./internals/scripts/deploy.sh"
    skip_cleanup: true
    on:
      branch: master
      tags: true

cache: yarn
